# CHAPTER ONE: Introduction

When Swedish climate activist Greta Thunberg was sixteen years old, she addressed a TED Talk crowd with a phrase that poignantly summarizes the state of the current world amidst global climate change: "The climate crisis has already been solved. We already have all the facts and solutions. All we have to do is to wake up and change" [@thunberg2018]. Science has demonstrated that climate change exists, how humans contribute to it, and its serious impacts [@ipcc2014; @schmittner2018]. We also know the solution to climate change is to stop emitting carbon dioxide (CO~2~) and other greenhouse gases (GHGs). And, we possess the technical means to achieve this now through available solar, wind, and hydroelectric technologies [@jacobson2017]. What is stopping us from solving the climate crisis is neither scientific nor technical but social in nature. @ehrhardtmartinez2015 argue that "GHG emissions are firmly rooted in the current organization of economic and social systems" (p. 199). It is mostly political and ideological barriers that stand in the way of solutions.  Climate change skepticism, which often falls along ideological divides, is known to be a major barrier that underlines the economic and social policies needed to successfully address climate change [@engelsPublicClimatechangeSkepticism2013; @guy2014; @hornsey2016]. Hence, Thunberg's statement that society needs to "wake up and change." 

<!-- CLIMATE CHANGE EFFECTS -->

Society must address climate change now, not later. There is a broad scientific consensus that anthropogenic (human-caused) climate change poses a serious threat to human and ecological stability [@harper2020; @oreskes2004; @schmittner2018]. Some of these risks include species extinctions and ecosystem loss; increased extreme weather events; food and water insecurity; decreases in quality of life; increases in illness and disease; and other societal disruptions [@ipcc2014, p. 65]. These effects are occurring even now, at 1°C (Celsius) of global warming above pre-industrial levels. These impacts are only predicted to increase at 1.5°C of global warming above pre-industrial levels. This is the temperature goal the Intergovernmental Panel on Climate Change (IPCC) and other scientific bodies have determined global temperature increases need to be limited to. The effects of climate change intensify at higher levels of warming [@carbonbrief2018].

<!-- CLIMATE CHANGE CAUSES -->

The primary cause of global warming is the emission of greenhouse gases, namely CO~2~, due to the burning of fossil fuels (e.g., coal, oil, natural gas). This matter-of-fact explanation belies the huge economic, political, and social drivers that underlie climate change [@dietz2007; @rosa2015]. According to @rosa2015, human impact on climate change is driven by a complex interaction between population, affluence, and technology, the latter term referring to "all other things, such as culture, institutional practices, and political processes" (p. 37). @rosa2015 summarize climate change using the *IPAT* equation:

:::{custom-style="Equation"}
$I_{mpact} = P_{opulation} \times A_{ffluence} \times T_{echnology}$.
:::

Population and affluence have been identified as the greatest contributors to climate change, namely through increased production and consumption [@jorgenson2010; @jorgenson2010a; @yorkSTIRPATIPATImPACT2003]. There is not always a one-to-one relationship between the population, affluence, and emissions. Nations that experience rapid population growth without similar increases in affluence (i.e., the Global South) typically have lower GHG emissions. Western nations, on the other hand, with lower rates of population growth but massive amounts of consumption via affluence have largely driven global climate change due to their massive emissions. 

Political forces and economic dispositions, as well as individual attitudes and behaviors, i.e., all other aspects of society embedded in the catch-all term "technology," can moderate the effect of population and affluence [@rosa2015]. For example, climate change research suggests that national political orientation and level of corruption (forms of "technology") have a relationship to emissions levels. Democratic societies with low levels of corruption emit fewer GHGs due to adoption and adherence to environmental policies when compared to democratic societies with high levels of corruption or authoritarian societies [@povitkina2018]. This example highlights the moderating effect of social institutions.



<!-- CLIMATE CHANGE SOLUTIONS -->

In fact, @sharma2012 argues that because “the fundamental causes of global climate change are social in nature...the most effective ways to counter the effects of global climate change would be social as well” (p. 35). To avoid the impacts of climate change, there is a serious need for action now in order to limit our warming to 1.5°C by 2050 [@ipcc2018a]. Direct effects on population and affluence are rather difficult to equitably achieve and can be on a generational time scale too slow for the change that is required of humanity. As a result, more effort has been focused on the *T* of *IPAT*.  Some of these solutions represent the literal interpretation as *T* for *technology*. Some propose geoengineering or carbon capture technologies as a solution to climate change. These technologies, however, are untested, expensive, and improbable on the timeline or scale needed to make a meaningful impact [@ipcc2014, p. 89; @mann2021, p. 150-164]. In the case of geoengineering (injecting particles into the atmosphere to reflect the sun away from the Earth), the technology itself may put humanity in continued danger [@sovacool2021]. Nevertheless, there are technologically feasible solutions. @jacobson2017 [see also @jacobson2015] argue that we currently have the ability to meet all our energy needs with extant wind, water, and solar technologies, and could do so in an economically feasible way. Other proposed solutions of a non-technical nature have included the introduction of carbon pricing to facilitate a shift from fossil fuels [@green2021], political reform toward more democratic leadership [@wynes2021], and  changes in individual behaviors [@sparkman2021; @wynes2018; see also @ehrhardtmartinez2015; @unitednationsenvironmentprogramme2020]. 

Another way for society to address climate change is through education, which is at the crux of this dissertation. Education may be a powerful tool through which individuals, communities, and nations can move society toward the changes needed to thwart 1.5°C of warming or worse. The vital role of education has been recognized by many. The United Nations Education, Scientific, and Cultural Organization [@unesco2015] states: "Education plays a paramount role in raising awareness and promoting behavioural change for climate change mitigation and adaption. It helps increase the climate change mitigation and adaptation capacity of communities by enabling individuals to make informed decisions" (p. 2). In considering the massive challenge that climate change poses, @kagawa2010a suggests that education can have a major role to play in deciding what direction human society moves:
  
>At such a moment of enormous human challenge, formal, nonformal, and informal education have a potentially crucial role to play. In both school age and adult learning communities, learners of all ages can be invited to take up the challenge of understanding and rethinking the world, of shattering assumptions, shibboleths and the taken-for-granted, of deliberating where to go at this critical fork in the road. (p. 5)


## Politics and Climate Change

@kagawa2010a recognize that mitigating climate disaster requires a shift in knowledge and perspective. This also suggests there is something to shift away from and that education may be one way to do it. This closely echoes Thunberg's (2018) statement that the primary solution to climate change is to "wake up and change." This implies something fundamental to the way one views the world needs to change. And, indeed, despite the overwhelming urgency for society to address climate change, it is the ideology that underlies society's economic, political, and cultural institutions that remains a key impediment to effective mitigation. 


Capitalist ideologies are deeply embedded in most modern societies. There are a number of socioeconomic concepts that explain how capitalism drives climate change. For example, the *ecological treadmill* [@rosa2015; @schnaiberg2002a] posits that capitalism creates a cycle of ever-increasing production and consumption, and, thus, ever-increasing ecological exploitation. Natural resources serve as inputs and pollution in the form of GHG emissions, air and water contaminants, and waste, often toxic, serve as outputs. As the treadmill, driven primarily by the need for growth, increases in speed, so too does the need for ecological inputs and destructive outputs [@schnaiberg2002a]. 


Research indicates that economic growth is a key economic factor driving climate change [@greiner2020a; @jorgenson2014]. While economic growth is often taken as a given, some research shows that at high levels, growth is associated with lower need satisfaction and higher energy usage [@vogel2021a]. Environmental justice movements have sprung up around the globe, specifically addressing economic growth and environmental destruction [@demaria2013; @martinezalier2012]. These movements question the ideology of capitalism and its fixation on economic growth [see also @kallis2020]. These movements see capitalism and unfettered growth as antithetical to a sustainable future. @mccrightPoliticalOrientationModerates2011 argues that "dealing with climate change, even acknowledging its reality, poses a fundamental critique of our current industrial capitalist economic system still driven by fossil fuels" (p. 244). It is easy to see how addressing climate change threatens the ideology at the core of much of humanity.

Though capitalism is a pervasive ideology, it does not often manifest itself as what one would consider a personal worldview or set of values. Instead, it appears rather strongly through various similar mechanisms that all underlie what can be referred to as *political conservatism*. For example, political conservatives have proclivities toward system justification, which is a view that the current system is legitimate and should be preserved [@vainio2011]. This has also been referred to as a tendency to defend the "dominant social paradigm" and along with it "science and technology, support for economic growth, and faith in material abundance and future prosperity" [@mccright2010, p. 107]. Both of these mechanisms inextricably support a capitalist economic system. 

Political conservatism has been indicted as one of the major barriers to instituting effective climate change policies and changes [@hornsey2016]. @mccrightPoliticalOrientationModerates2011 argues that conservative ideology generally serves to protect the status quo and defend capitalism. Since climate change is a major consequence of capitalist activity, conservative ideology naturally opposes climate science and its solutions, either through denial, skepticism, or inactivism [@mann2021]. This leads to greater polarization of politicians and greater bias in the news media [@mccright2010], which in turn, solidifies political ideology. According to McCright (2011), such ideological divisions have "serious ramifications for our society’s collective definition of reality" (p. 246). 

Ideological divisions and polarization of politicians can lead to the stifling of mitigation efforts. Research by @fairbrother2019 on European support for carbon taxes found that support was tied to political ideology and trust in one's politicians. More conservative individuals were less likely to support carbon taxes. Likewise, those with lower trust in politicians or their government were also less likely to support carbon taxes. Political ideology can have a measured influence on the environment, as well. For example, states with strong environmentalism, as measured by state legislatures' support of environmental legislation, emit fewer greenhouse gases [@dietz2015].

While skepticism in climate change is decreasing [@fairbrother2019; @hamilton2015; @howe2015], there is still a concerted effort to treat climate change as a partisan issue in need of discussion rather than action [@mann2021]. Although there is a strong scientific consensus regarding climate change [@lynas2021],  @mccrightPoliticalOrientationModerates2011 points out that climate change is often treated as a debate in political and media arenas, and that this "represents a major victory by forces of [conservative ideology] in their efforts to prevent a regulatory policy to deal with climate change" (p. 245-246).

## The Role of Education

The ideological dimensions of climate change discussed above imply what society needs to wake up from and change. Education can help facilitate this. Indeed @lambeir2008 argue that it is not possible to discuss a social problem without connecting it to education: "The very understanding of something as a social problem already implies the intention to solve it, and this solution already also implies, in the current climate, some kind of learning" (p. 445). @bridges2008 writes that “It is difficult to conceive of educational interventions disconnected from some sort of hope for social improvement” (p. 467). In fact, education has long been seen as an "effective instrument of social progress" [@dewey1897]. As early as the 1900s, education had come to be conceived of as a way to "develop individuals for effectiveness in a social world" [@deboer1991, p. 67]. For instance, science education was thought of as invaluable in order to protect public health through sanitation and hygiene. Science education was later promoted as a means to boost national security and economic success [@deboer1991; @sharma2012]. Today, education among women is seen as a vital means to help slow population growth and improve life expectancy for themselves and their children [@baker2011; @liu2020].


As a social institution with the potential to address social issues, it should come as no surprise that education should play an important role in lessening the effects of the climate crisis by fostering change at individual, community, and national levels. This is why @unesco2015 considers education "paramount" in fighting climate change and why it is included in numerous United Nations agreements, including the Paris Agreement [@reid2019]. Education among adolescents may be especially poignant because their worldviews have not yet solidified, they can influence household behavior and values [@ballantyne1998; @lawson2018; @lawsonChildrenCanFoster2019; @maddox2011], and they will make "behavioural choices that will structure the rest of their lives, and must grow up accustomed to a lifestyle" which aims to meet proposed climate targets [@wynes2017, p. 2]. 


Science education in particular will be important in advancing these changes. According to @sharma2012, science education "should prepare students to play an active role as citizens in making the state as well as the society responsive to the issue in ways that are sustainable and evidence-based" (p. 48). Scientific literacy, which is the outcome of science education, therefore, gives humanity the tools it needs for understanding climate change and its solutions [@mccaffrey2012].

Science education can make important shifts in knowledge. However, it can also cause important shifts in values, beliefs, and behavior. For example, science education has been found to positively influence climate change attitudes, even protecting against the effects of political orientation [@list2020; @stevenson2014; @vanderlinden2018]. Research has shown that science education can also promote positive environmental behaviors among adolescents [@list2020; @stevenson2018]. Education of youth can also affect parents' climate change beliefs through intergenerational learning [@lawson2018; @lawsonChildrenCanFoster2019]. Micro-level changes such as these have been pointed to as potential catalysts of broader, macro-level changes needed to address a global issue [@ehrhardtmartinez2015; @unitednationsenvironmentprogramme2020, p. 62-75].

The United Nations identified education as a key strategy for climate action many decades ago in 1992 [@reid2019]. It is now 2021. Climate change education has been integrated into science curricula internationally for quite some time, heralded by such efforts as the UN's Education for Sustainable Development program, among others. With all this effort and the urgency of the climate crisis itself, there needs to be some assessment of education's effect on climate change. Only a handful of studies, however, have assessed the impact of education on climate change. The scant literature on this topic has considered education in terms of adult literacy [@jorgenson2003], secondary school enrollment [@jorgenson2005], educational spending [@mayer2013], college education levels [@jorgenson2018], and years of schooling [@ergas2021; @kelly2020]. No prior research exists that examines educational performance, especially in science, and its possible broader impact on GHG emissions. 

## Purpose of the Study

The purpose of this dissertation is to assess the extent to which scientific literacy, as the primary outcome of science education, may have a measurable effect on a nation's carbon emissions. This research would be the first to link trends in scientific literacy with such macro-level environmental impacts. The following research questions will be addressed: 1) what is the relationship between changes in scientific literacy  and per-capita CO~2~ emissions; 2) does the relationship differ when examining changes in male and female scientific literacy; and 3) do these relationships vary for developed and less-developed countries. To answer these questions, the research will analyze scientific literacy scores as measured by the Programme for International Student Assessment (PISA) and national carbon emissions over a twelve year period. These findings will address a large gap in the research on climate change impacts of education. More importantly, this dissertation may bolster support of science education as an effective means of mitigating climate change. This increased focus on fostering scientific literacy in adolescents can shift national attitudes, behaviors, and policy support, necessary for furthering societal change to help mitigate climate change.




`r officer::run_pagebreak()`
