# VITA

Anthony Schmidt was born in New York and raised in Florida. He earned a bachelor’s degree in anthropology from the University of South Florida in 2006. After graduating, Anthony moved to Busan, South Korea to teach English as a foreign language. There, he began a distance education Master’s program in language, literacy, and cultural education from Indiana University, Bloomington. Anthony taught middle school and eventually university courses at Pukyong National University before returning to the United States in 2014 to take a position at the University of Tennesee, Knoxville’s English Language Institute (ELI).

In 2018, while working full-time at the ELI, Anthony began graduate coursework in the College of Education, Health, and Human Sciences. He then applied and was admitted to the Evaluation, Statistics, and Methodology (then Measurement) program. In 2019, while continuing coursework, Anthony change careers and became a data visualization designer at the College and University Professional Association for Human Resources. In 2021, Anthony took a position as a data scientist at Amplify Education, where he currently works at the time of writing.
